
((digest . "2a3ca18a9b5aa727fc85ce01f32651d1") (undo-list nil (#(";;              (define-key eshell-mode-map \"C-M-k\" 'backward-kill-line)))
" 0 3 (fontified t face font-lock-comment-delimiter-face) 3 16 (fontified t face font-lock-comment-delimiter-face) 16 17 (fontified t face font-lock-comment-face) 17 27 (fontified t face font-lock-comment-face) 27 44 (fontified t face font-lock-comment-face) 44 45 (fontified t face font-lock-comment-face) 45 50 (fontified t face font-lock-comment-face) 50 51 (fontified t face font-lock-comment-face) 51 72 (fontified t face font-lock-comment-face) 72 73 (fontified t face font-lock-comment-face) 73 74 (fontified t face font-lock-comment-face) 74 75 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face font-lock-comment-face))) . 4829) ((marker) . -75) nil (#(";;           '(lambda ()
" 0 3 (fontified t face font-lock-comment-delimiter-face) 3 13 (fontified t face font-lock-comment-delimiter-face) 13 15 (fontified t face font-lock-comment-face) 15 21 (fontified t face font-lock-comment-face) 21 24 (fontified t face font-lock-comment-face) 24 25 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face font-lock-comment-face))) . 4829) ((marker) . -25) nil (#(";; (add-hook 'eshell-mode-hook
" 0 3 (fontified t face font-lock-comment-delimiter-face) 3 4 (help-echo "Looks like a toplevel defun: escape the parenthesis" fontified t face font-lock-comment-face) 4 12 (fontified t face font-lock-comment-face) 12 30 (fontified t face font-lock-comment-face) 30 31 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face font-lock-comment-face))) . 4829) ((marker) . -31) nil (#("   (kill-region (region-beginning) (region-end))))
" 0 50 (fontified t) 50 51 (rear-nonsticky t fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face))) . 4829) ((marker . 4829) . -51) ((marker . 4829) . -51) ((marker . 4829) . -51) ((marker . 4829) . -51) ((marker . 4829) . -51) ((marker) . -51) nil (#("     (backward-kill-word 1)
" 0 27 (fontified t) 27 28 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face))) . 4829) ((marker) . -28) nil (#(" (if (> (point-max) (point))
" 0 1 (fontified t) 1 2 (fontified t) 2 3 (fontified t face font-lock-keyword-face) 3 4 (fontified t face font-lock-keyword-face) 4 5 (fontified t) 5 7 (fontified t) 7 8 (fontified t) 8 9 (fontified t) 9 10 (fontified t) 10 11 (fontified t) 11 12 (fontified t) 12 13 (fontified t) 13 14 (fontified t) 14 15 (fontified t) 15 16 (fontified t) 16 17 (fontified t) 17 18 (fontified t) 18 19 (fontified t) 19 20 (fontified t) 20 21 (fontified t) 21 22 (fontified t) 22 23 (fontified t) 23 24 (fontified t) 24 25 (fontified t) 25 26 (fontified t) 26 27 (fontified t) 27 28 (fontified t) 28 29 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face))) . 4829) ((marker) . -29) nil (#("(defun-eshell-cmdline \"C-M-k\"
" 0 22 (fontified t) 22 25 (fontified t face font-lock-string-face) 25 28 (fontified t face font-lock-string-face) 28 29 (fontified t face font-lock-string-face) 29 30 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face))) . 4829) ((marker*) . 30) ((marker) . -1) ((marker) . -30) nil (#("; C-M-k
" 0 1 (fontified t face font-lock-comment-delimiter-face) 1 2 (fontified t face font-lock-comment-delimiter-face) 2 7 (fontified t face font-lock-comment-face) 7 8 (fontified t face (jaspace-highlight-eol-face jaspace-highlight-eol-face font-lock-comment-face))) . 4829) (t 20292 . 22411) ((marker . 4829) . -8) ((marker . 4829) . -8) ((marker) . -8) ((marker) . -8) nil (4873 . 4874) nil (#("e" 0 1 (fontified t)) . -4873) nil (#("q" 0 1 (fontified t)) . -4874) nil undo-tree-canary))
