
((digest . "6f564ce32e697a99a96964ae2f7b5e64") (undo-list nil (12 . 16) nil (#("P" 0 1 (fontified t face font-lock-comment-face)) . -12) nil (#("e" 0 1 (fontified t face font-lock-comment-face)) . -13) nil (#("r" 0 1 (fontified t face font-lock-comment-face)) . -14) nil (#("l" 0 1 (fontified t face font-lock-comment-face)) . -15) nil (#("I" 0 1 (fontified t face font-lock-comment-face)) . -16) nil (#("O" 0 1 (fontified t face font-lock-comment-face)) . -17) nil (12 . 18) (#("perl" 0 4 (fontified t face font-lock-comment-face)) . -12) nil (11 . 16) nil (#("." 0 1 (fontified t face font-lock-comment-face)) . -11) nil (7 . 12) nil (#("." 0 1 (fontified t face font-lock-comment-face)) . -7) nil (1 . 8) nil (1 . 2) nil (#("#!/usr/bin" 0 1 (fontified t font-lock-multiline t face font-lock-comment-delimiter-face) 1 10 (fontified t font-lock-multiline t face font-lock-comment-face)) . 50) nil (49 . 60) nil (48 . 49) nil (47 . 48) nil (46 . 47) (t 20363 . 43365) nil (#("abc def ;" 0 3 (font-lock-multiline t fontified t) 3 7 (font-lock-multiline t fontified t) 7 8 (font-lock-multiline t fontified t) 8 9 (font-lock-multiline t fontified t)) . 46) ((marker . 62) . -9) nil (#("
" 0 1 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face))) . 55) ((marker . 62) . -1) nil (55 . 56) nil (54 . 55) nil (#("g" 0 1 (font-lock-multiline t fontified t)) . 54) nil (#(";" 0 1 (font-lock-multiline t fontified t)) . 55) nil (55 . 56) nil (54 . 55) nil (#(";" 0 1 (font-lock-multiline t fontified t)) . -54) nil (#("
" 0 1 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face))) . -55) nil (55 . 56) nil (54 . 55) nil (47 . 54) nil (#("b" 0 1 (font-lock-multiline t fontified nil)) . -47) nil (#("s" 0 1 (font-lock-multiline t fontified t face font-lock-type-face)) . -48) nil (45 . 49) nil (44 . 45) nil (43 . 44) nil (42 . 43) nil (34 . 42) (#("war" 0 3 (fontified t font-lock-multiline t)) . -34) nil (29 . 37) nil (28 . 29) nil (22 . 28) (#("str" 0 3 (font-lock-multiline t fontified nil face font-lock-function-name-face)) . -22) nil (18 . 25) nil (#("
prin aaa;

print

    ;



aaa




    setr



    " 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face)) 1 5 (fontified t font-lock-multiline t) 5 10 (fontified t font-lock-multiline t) 10 11 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face)) 11 12 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face)) 12 17 (font-lock-multiline t fontified t face cperl-nonoverridable-face) 17 18 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 18 19 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 19 24 (font-lock-multiline t fontified t) 24 25 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 25 26 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 26 27 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 27 28 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 28 31 (font-lock-multiline t fontified t) 31 32 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 32 33 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 33 34 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 34 35 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 35 36 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 36 40 (font-lock-multiline t fontified t) 40 44 (font-lock-multiline t fontified t) 44 45 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 45 46 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 46 47 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 47 48 (font-lock-multiline t fontified t face (jaspace-highlight-eol-face)) 48 52 (font-lock-multiline t fontified t face (underline default))) . 18) ((marker . 12) . -40) ((marker . 34) . -52) ((marker . 34) . -52) nil (65 . 70) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 65) 69 nil (64 . 69) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 64) 68 nil (63 . 68) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 63) 67 nil (62 . 67) nil (53 . 62) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 53) 57 nil (52 . 57) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 52) 56 nil (51 . 56) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 51) 55 nil (50 . 55) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 50) 54 nil (49 . 54) nil (45 . 49) nil (44 . 45) nil (43 . 44) nil (42 . 43) nil (41 . 42) nil (36 . 41) (#("    " 0 4 (font-lock-multiline t fontified t face (underline default))) . 36) 40 nil (35 . 40) nil (29 . 35) nil (28 . 29) nil (27 . 28) nil (18 . 27) nil (17 . 18) nil (16 . 17) nil (15 . 16) nil (5 . 15) (#("LW" 0 2 (fontified t font-lock-multiline t)) . -5) nil (1 . 7) nil (#("LWP
" 0 3 (fontified t) 3 4 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#("aaaa
" 0 4 (fontified t) 4 5 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#(";
" 0 1 (fontified t) 1 2 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#("aaaa
" 0 4 (fontified t) 4 5 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . 1) nil (18 . 19) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . -16) nil (#(";" 0 1 (fontified t)) . -17) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . -18) nil (#("
" 0 1 (fontified t font-lock-multiline t face (jaspace-highlight-eol-face))) . -19) (t 20363 . 28912) nil (22 . 23) nil (20 . 22) nil (#("p" 0 1 (font-lock-multiline t fontified t)) . -20) nil (#("r" 0 1 (font-lock-multiline t fontified t)) . -21) nil (#("i" 0 1 (font-lock-multiline t fontified t)) . -22) nil (20 . 23) nil (19 . 20) nil (18 . 19) nil (17 . 18) nil (16 . 17) nil (15 . 16) nil (11 . 15) (#("aaa" 0 3 (font-lock-multiline t fontified nil)) . -11) nil (10 . 14) nil (2 . 3) nil (1 . 2) (t 20363 . 28757) nil (7 . 8) nil (6 . 7) nil (5 . 6) nil (1 . 5) (t 65535 . 65535)))
