
((digest . "3c78f304ac7582b48ef516dbfde747ff") (undo-list nil (#("// " 0 3 (face font-lock-comment-face)) . -883) (#("// " 0 3 (face font-lock-comment-face)) . -875) (#("// " 0 3 (face font-lock-comment-face)) . -865) (#("// " 0 3 (face font-lock-comment-face)) . -743) (#("// " 0 3 (face font-lock-comment-face)) . -668) (#("// " 0 3 (face font-lock-comment-face)) . -636) (#("// " 0 3 (face font-lock-comment-face)) . -603) (#("// " 0 3 (face font-lock-comment-face)) . -548) (#("// " 0 3 (face font-lock-comment-face)) . -491) (#("// " 0 3 (face font-lock-comment-face)) . -400) (#("// " 0 3 (face font-lock-comment-face)) . -351) (#("// " 0 3 (face font-lock-comment-face)) . -299) (#("// " 0 3 (face font-lock-comment-face)) . -253) (#("// " 0 3 (face font-lock-comment-face)) . -210) (#("// " 0 3 (face font-lock-comment-face)) . -187) (#("// " 0 3 (face font-lock-comment-face)) . -166) (#("// " 0 3 (face font-lock-comment-face)) . -153) (#("// " 0 3 (face font-lock-comment-face)) . -119) (#("// " 0 3 (face font-lock-comment-face)) . -114) (#("// " 0 3 (face font-lock-comment-face)) . -106) (#("// " 0 3 (face font-lock-comment-face)) . -60) (#("// " 0 3 (face font-lock-comment-face)) . -16) (#("// " 0 3 (face font-lock-comment-face)) . -1) 954 nil (#("window.onload=function(){
Object = document.getElementsByTagName('select')[0];
//↑ページ内のselectの[0]番目を得る
Object.onchenge=function(){alert(1);}
//↑onchangeイベントの処理を追加する
}

" 7 13 (face font-lock-function-name-face) 14 22 (face font-lock-keyword-face) 65 73 (face font-lock-string-face) 79 103 (face font-lock-comment-face) 103 110 (help-echo "missing ; after statement" point-entered js2-echo-error) 110 118 (face font-lock-function-name-face help-echo "missing ; after statement" point-entered js2-echo-error) 118 119 (help-echo "missing ; after statement" point-entered js2-echo-error) 119 127 (face font-lock-keyword-face help-echo "missing ; after statement" point-entered js2-echo-error) 127 140 (help-echo "missing ; after statement" point-entered js2-echo-error) 141 165 (face font-lock-comment-face) 165 166 (help-echo "missing ; after statement" point-entered js2-echo-error)) . -1) (t 20352 . 24180) ((marker) . -165) ((marker) . -166) ((marker) . -103) ((marker) . -140) ((marker) . -168)))
